### ISSUE TITLE
Different Register List

### ISSUE THREAD

**Issue by deddy11** [stm32duino/ISM330DLC#3]
in ISM330DLC_ACC_GYRO_Driver.h file, there are some register address macros that I can't find in ISM330DLC datasheet (revision 3 13-Nov-2018). For example:
```
#define ISM330DLC_ACC_GYRO_STEP_COUNTER_L  	0X4B
#define ISM330DLC_ACC_GYRO_STEP_COUNTER_H  	0X4C
```
Also I can't find register bit STEP_OVERFLOW and COUNT_DELTA in FUNC_SRC register which are used in ISM330DLC_ACC_GYRO_Driver.c file.
Is there any newer datasheet that this library refers to? Please help. Thanks.

**Comment by cparata** [comment]
Hello @deddy11 ,
thanks to have submit this issue. Actually, it is an issue in the sensor library. The datasheet is correct.
I will update the sensor driver fixing this issue.
Best Regards,
Carlo

**Comment by deddy11** [comment]
Hai @cparata , 
thanks for your fast response. I will wait for your update then.

**Comment by cparata** [comment]
Hi @deddy11 ,
I updated the source code. Let me know if you find any other misalignment with the datasheet in the code. If no, I will generate a new release of the library.
Best Regards,
Carlo

**Comment by deddy11** [comment]
Thanks @cparata , I have pulled your update. I will tell you if I find any other misalignment.

**Comment by deddy11** [comment]
Hi @cparata ,
I found these register which are not included yet
```
#define ISM330DLC_ACC_GYRO_INT_OIS  	0X6F
#define ISM330DLC_ACC_GYRO_CTRL1_OIS  	0X70
#define ISM330DLC_ACC_GYRO_CTRL2_OIS  	0X71
#define ISM330DLC_ACC_GYRO_CTRL3_OIS  	0X72
```
So there aren't any functions that set/get these registers value. 
Would you mind to add them into the library?
Thanks.

**Comment by cparata** [comment]
Hello @deddy11 ,
at the moment there is no plan to add the support to the OIS functionality. Any contribute from the community is welcome to improve the library.
Best Regards,
Carlo

**Comment by deddy11** [comment]
Hi @cparata ,
I want to verify about register TAP_THS_6D bit D4D_EN. In the datasheet, it should be set to 0 to be enabled, but in the library it should be passed by 1 to be enabled. I doubt the datasheet is right because the default value will enable 4D orientation detection so the Z-axis position detection is disabled. Which one is true?
Thanks

**Comment by cparata** [comment]
Hi @deddy11 ,
regarding the D4D_EN bit, if you put it to 1 you enable the 4D orientation and so the Z-axis position detection is disabled. If you leave the D4D_EN bit to 0, the 6D orientation is enabled and the Z-axis position detection is enabled as well. Normally, in the code, I usually use the 6D orientation and so I leave that bit to 0.
You can check it in the relative [Application Note](https://www.st.com/resource/en/application_note/an5125-ism330dlc-3d-accelerometer-and-3d-gyroscope-with-digital-output-for-industrial-applications-stmicroelectronics.pdf), paragraphs 5.4.1 and 5.4.2.
Best Regards,
Carlo

**Comment by deddy11** [comment]
Hi @cparata ,
Sorry for late reply. Thanks for your answer. I will close this issue.
